FROM python:3.8.12

WORKDIR /app

COPY ./ /app/
COPY ./.aws /root/.aws

RUN apt-get update
RUN apt-get install -y zip
RUN apt-get install -y parallel
RUN pip install -r requirements.txt

CMD ["tail", "-f", "/dev/null"]